### ISSUE TITLE
array too small

### ISSUE THREAD

**Issue by krisabo** [jontio/libaeroambe#2]
In "ambe4800x3600.c" line 163
`float f0, Cik[5][18], flokl[57], deltal[57];`

The first dimension of `CiK[][]` is too small? 
```
for (i = 1; i <= 8; i++)
{
   Cik[i][1] = Ri[i];
...
}
```
My compiler gave me a warning.

**Comment by jontio** [comment]
Thanks for finding that. That indeed does not look right and could cause the dreaded segmentation fault. I have changed it to a 9 x 18 matrix.

Cheers,
Jonti
