### ISSUE TITLE
 Maybe need administrative privileges.

### ISSUE THREAD

**Issue by justin983** [jontio/libaeroambe#3]
i complied libaeroambe on windows but when im doing make install im getting this error

[100%] Built target gmock_main
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: C:/Program Files (x86)/mbe/lib.  Maybe need
  administrative privileges.

make: *** [Makefile:115: install] Error 1

**Comment by jontio** [comment]
I have found that installs on Windows can be a bit strange and quite often need a bit of tweaking. The install prefix for a system assuming a 64 bit MSYS2 setup should be /mingw64 so if you want to use that prefix then use something like...

`cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/mingw64/ ..`

When using the cmake command. If you really did want to install it into the program folder I think you would have to start ming64 with administration privileges as Windows mingw64 doesn't have a sudo command as far as I can tell.

Something like the following should be what would be needed to clone build and install on windows...

```bash
pacman -S --needed --noconfirm git mingw-w64-x86_64-toolchain autoconf libtool mingw-w64-x86_64-qt5 mingw-w64-x86_64-cmake mingw-w64-x86_64-libvorbis
git clone https://github.com/jontio/libaeroambe
cd libaeroambe/mbelib-master
mkdir build && cd build
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/mingw64/ ..
mingw32-make
mingw32-make DESTDIR=/../ install
cp libmbe.dll /mingw64/bin/
cd ../../libaeroambe
qmake
mingw32-make
cp release/*.dll /mingw64/bin/
cp release/*.dll.a /mingw64/lib/
cd ../..
```

**Comment by justin983** [comment]
Thanks These command Worked Like MAGIC !!!
